### PR TITLE
Add --host option to dev command (Closes #1)

### LINKED ISSUE #1: Request: Allow passing host to webpack dev server (support containers)
I'm trying to start learning how roam extensions are built but I am trying to keep the dev environment in docker containers. I have managed to build and launch the dev server for my test extension [as per the instructions](https://developer.roamjs.com/roamjs-scripts/dev). However, because this is executed inside a docker container, and the host is [hardcoded to `127.0.0.1`](https://github.com/dvargas92495/roamjs-scripts/blob/d653e3f62424827b2cd284df605f76afa7e2faf8/src/index.ts#L250), I cannot connect to it from outside the container, even with the right port bindings in place.

For this scenario, I'd like to set the host to `0.0.0.0` as [instructed here](https://okteto.com/docs/tutorials/webpack/). Ideally without having to patch these dependencies.

**Would you consider adding a new command-line option or even env var to allow overriding the webpack dev server host? or even even a flag to set it to `0.0.0.0`?**

Thanks.

### PR DESCRIPTION
**Pull request by jdevera**
When running the dev command on a Docker container, the default host value of 127.0.0.1 that gets passed to the Webpack Dev Server will allow connections only from within the container. In order to connect from the docker host, the Webpack Dev Server needs to take 0.0.0.0 as the host parameter.

This changeset introduces a new optional argument to the dev command, `--host` that will take the address that will be passed as a host to Webpack Dev Server. By default this 127.0.0.1.

Relates to #1

### CODE REVIEW

**Comment by jdevera** [comment]
I could not find the source of the docs at https://developer.roamjs.com/ to update them. Are they on a public repo?

**Review by dvargas92495 — APPROVED** [review]
Looks great! Thanks for this!

Docs are managed by gitbook, I could update them. Still not sure if that's where I want them permanently

**Comment by jdevera** [comment]
Oh, that was fast, I marked it as draft and repushed because I got the wrong email in the commit 🤦

**Comment by jdevera** [comment]
@dvargas92495 are releases automated?

**Comment by dvargas92495** [comment]
automated on version changes to package json, which I just pushed! 0.11.0 should be live

**Pull request merged**
